//! Q4K paired-epilogue GEMV program kernels.

use fusor_tile_ir::tile::{
    quantized::ggml::BlockCoords, Mask, Program, QuantizedDot, ScalarIndex, Storage, Tile,
    TileBlock,
};
use fusor_tile_ir::{
    GgmlQuantFormat, QuantizedMatrix, TileLiteral, TileReduceOp, WorkgroupAxis, F32,
};

use crate::grid::{q4k_ggml_iteration, q4k_lane_decomposition, Q4KGgmlIterationRequest};
use crate::types::{matrix_shape, PairedEpilogue};

fn qgemv_q4k_paired_tile_name_from_env() -> &'static str {
    match std::env::var("FUSOR_Q4K_PAIRED_TILE")
        .or_else(|_| std::env::var("FUSOR_Q4K_SWIGLU_TILE"))
        .as_deref()
    {
        Ok("4x1") => "4x1",
        Ok("2x2") => "2x2",
        Ok("2x4") => "2x4",
        Ok("8x1") => "8x1",
        Ok("4x4") => "4x4",
        Ok("8x2") | _ => "8x2",
    }
}

/// Stable short name for the env-selected Q4K paired GEMV tile.
pub fn qgemv_q4k_paired_tile_name() -> &'static str {
    qgemv_q4k_paired_tile_name_from_env()
}

/// Number of output pair columns covered by one workgroup for the env-selected
/// Q4K paired GEMV tile.
pub fn qgemv_q4k_paired_cols_per_workgroup() -> u32 {
    match qgemv_q4k_paired_tile_name_from_env() {
        "4x1" | "2x2" => 4,
        "2x4" | "8x1" => 8,
        "4x4" | "8x2" => 16,
        _ => unreachable!("qgemv_q4k_paired_tile_name_from_env returns a known tile name"),
    }
}

/// Inputs and launch geometry for the Q4K paired-epilogue GEMV kernels.
///
/// These kernels consume a Q4K matrix whose columns are laid out as
/// `[gate columns, up columns]`. Each kernel computes both halves for a
/// column pair, applies `epilogue` in-register, and writes the paired result.
///
/// ```no_run
/// # use fusor_tile_ir::{tile, GgmlQuantFormat, Shape, F32};
/// # use fusor_tile_ir_kernels::{
/// #     PairedEpilogue, Q4KPairedGgml, qgemv_q4k_paired, quantized_matrix,
/// # };
/// let epilogue =
///     PairedEpilogue::with_extras("mul", 0, |tiles| tiles[0].clone() * tiles[1].clone());
/// let ir = tile::build(|program| {
///     let a = program.storage_read::<F32, 2>(Shape::new([1, 4096]));
///     let b = quantized_matrix(program, GgmlQuantFormat::Q4K, 4096, 8192);
///     let y = program.storage_write::<F32, 2>(Shape::new([1, 4096]));
///     qgemv_q4k_paired(
///         program,
///         Q4KPairedGgml {
///             a: &a,
///             b: &b,
///             y: &y,
///             pair_cols: 4096,
///             m_rows: 1,
///             workgroups_x: 1,
///             epilogue: &epilogue,
///             extras: &[],
///         },
///     );
/// });
/// ```
pub struct Q4KPairedGgml<'a> {
    /// Single-row or batched activation matrix.
    pub a: &'a Storage<F32, 2>,
    /// Q4K matrix with `pair_cols * 2` columns.
    pub b: &'a QuantizedMatrix,
    /// Output matrix with `pair_cols` columns.
    pub y: &'a Storage<F32, 2>,
    /// Number of gate/up pairs in `b`.
    pub pair_cols: u32,
    /// Number of rows from `a` and `y` covered by the launch.
    pub m_rows: u32,
    /// Preferred dispatch width on X. Clamped to the kernel's total workgroup count.
    pub workgroups_x: u32,
    /// Register-level operation applied to each `(gate, up)` pair.
    pub epilogue: &'a PairedEpilogue,
    /// One-dimensional extra tensors consumed by `epilogue`.
    pub extras: &'a [Storage<F32, 1>],
}

/// Build a Q4K paired-epilogue GEMV body.
pub fn qgemv_q4k_paired(program: &mut Program, spec: Q4KPairedGgml<'_>) {
    match qgemv_q4k_paired_tile_name_from_env() {
        "4x1" => qgemv_q4k_paired_ggml::<4, 1, 2, 128>(program, spec),
        "4x4" => qgemv_q4k_paired_ggml::<4, 4, 8, 128>(program, spec),
        "8x1" => qgemv_q4k_paired_ggml::<8, 1, 2, 256>(program, spec),
        "8x2" => qgemv_q4k_paired_ggml::<8, 2, 4, 256>(program, spec),
        "2x2" => qgemv_q4k_paired_ggml::<2, 2, 4, 64>(program, spec),
        "2x4" => qgemv_q4k_paired_ggml::<2, 4, 8, 64>(program, spec),
        _ => unreachable!("qgemv_q4k_paired_tile_name_from_env returns a known tile name"),
    }
}

/// Q4K paired-epilogue qgemv body. The kernel reduces the gate and up halves
/// of a `[gate; up]` matmul output and applies the supplied `PairedEpilogue`
/// in-register before the single output store. Per-shape entry points are
/// generated by the `q4k_paired_entrypoints!` macro.
fn qgemv_q4k_paired_ggml<
    const SUBGROUPS: u32,
    const PAIRS_PER_SUBGROUP: usize,
    const DOTS_PER_SUBGROUP: usize,
    const BLOCK: usize,
>(
    program: &mut Program,
    spec: Q4KPairedGgml<'_>,
) {
    let Q4KPairedGgml {
        a,
        b,
        y,
        pair_cols,
        m_rows,
        workgroups_x,
        epilogue,
        extras,
    } = spec;
    debug_assert_eq!(
        extras.len(),
        epilogue.extras_count(),
        "kernel extras count must match epilogue arity"
    );
    const SUBGROUP_SIZE: u32 = 32;
    debug_assert_eq!(SUBGROUPS * SUBGROUP_SIZE, BLOCK as u32);
    debug_assert_eq!(DOTS_PER_SUBGROUP, PAIRS_PER_SUBGROUP * 2);
    debug_assert_eq!(b.format, GgmlQuantFormat::Q4K);
    debug_assert_eq!(b.cols, pair_cols * 2);

    let [_, k] = matrix_shape(&a.view().layout);
    let cols_per_workgroup = SUBGROUPS * PAIRS_PER_SUBGROUP as u32;
    let cols_workgroups = pair_cols.div_ceil(cols_per_workgroup);
    let m_rows = m_rows.max(1);
    let total_workgroups = cols_workgroups * m_rows;
    let workgroups_x = workgroups_x.min(total_workgroups.max(1));
    let dispatch_y = total_workgroups.div_ceil(workgroups_x);
    let block_count = k.div_ceil(256);
    let block_iterations = block_count.div_ceil(4);
    let full_block_iterations = block_count.is_multiple_of(4);
    let full_cols = pair_cols.is_multiple_of(cols_per_workgroup);
    let b_cloned = b.clone();

    program.program_grid::<BLOCK>([workgroups_x, dispatch_y, 1], |program| {
        let workgroup_idx = program.program_id(WorkgroupAxis::X)
            + program.program_id(WorkgroupAxis::Y) * workgroups_x;
        let row = workgroup_idx.clone() / cols_workgroups;
        let col_workgroup = workgroup_idx % cols_workgroups;
        let row_in_bounds = row.clone().lt(m_rows);
        let col_group_base = col_workgroup * cols_per_workgroup;
        let subgroup_col_base = program.subgroup_id() * PAIRS_PER_SUBGROUP as u32;
        let col0 = col_group_base + subgroup_col_base;
        let lane = program.subgroup_lane();
        let q4k_lane = q4k_lane_decomposition(&lane);

        let zero = TileLiteral::f32(0.0);
        let sums: [Tile; DOTS_PER_SUBGROUP] = program.loop_fold_n::<DOTS_PER_SUBGROUP, _>(
            TileReduceOp::Sum,
            block_iterations,
            [zero; DOTS_PER_SUBGROUP],
            |program, loop_index| {
                let pass = q4k_ggml_iteration(
                    program,
                    Q4KGgmlIterationRequest {
                        loop_index,
                        a,
                        row: row.clone(),
                        block_count,
                        full_block_iterations,
                        lane: &q4k_lane,
                        base_mask: row_in_bounds.clone(),
                    },
                );

                let dot = |program: &mut TileBlock<'_>, col: ScalarIndex, mask: Mask| {
                    let coords = BlockCoords::new(&pass.block, &q4k_lane.iq, &q4k_lane.ir, &col);
                    program.quantized_dot(QuantizedDot::ggml_q4k(
                        pass.activations.clone(),
                        &b_cloned,
                        coords,
                        mask,
                        0.0,
                    ))
                };

                std::array::from_fn(|idx| {
                    let offset = idx % PAIRS_PER_SUBGROUP;
                    let gate = col0.clone() + offset as u32;
                    let col = if idx < PAIRS_PER_SUBGROUP {
                        gate.clone()
                    } else {
                        gate.clone() + pair_cols
                    };
                    let mask = if full_cols {
                        pass.in_bounds.clone()
                    } else {
                        pass.in_bounds.clone().and(gate.lt(pair_cols))
                    };
                    dot(program, col, mask)
                })
            },
        );

        for offset in 0..PAIRS_PER_SUBGROUP {
            let col = col0.clone() + offset as u32;
            let gate = program.subgroup_reduce_sum(sums[offset].clone());
            let up = program.subgroup_reduce_sum(sums[offset + PAIRS_PER_SUBGROUP].clone());
            let store_lane = if full_cols {
                lane.eq(0)
            } else {
                lane.eq(0).and(col.lt(pair_cols))
            };
            let mask = store_lane.and(row_in_bounds.clone());
            // Load any per-column extras (e.g. bias vectors) at the current
            // output column. Indexing is `extras[k][col]` — extras are 1D
            // tensors of length `pair_cols`.
            let extra_tiles: Vec<Tile> = extras
                .iter()
                .map(|extra| {
                    program.load(
                        extra.at(col.clone()),
                        mask.clone(),
                        fusor_tile_ir::TileLiteral::f32(0.0),
                    )
                })
                .collect();
            let value = epilogue.apply(gate, up, &extra_tiles);
            program.store(y.at((row.clone(), col)), value, mask);
        }
    });
}
