[package]
name = "fusor-conformance"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
fusor = { path = "../fusor", features = ["graphvis"] }
rand = { version = "0.9", default-features = false, features = ["std", "std_rng"] }
half = "2.4"
fusor-types = { path = "../types" }
thiserror.workspace = true
bytemuck = "1.14"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
