//! Quantized contraction lowerings, the two activation packings, and
//! `qrepack`.
//!
//! The reference's nine `qmatmul_direct_selector` arms become ten
//! independent rules with divisibility as the only legality guard.
//! `N >= 8192`, `K <= 1024` and `storage >= 32 KiB` become **nothing** here
//! — they are cost terms in W6 — so N = 8191 degrades continuously instead
//! of falling several arms down a first-match list. The `cached: bool`
//! variant flag is dropped: it was a pipeline-cache-slot distinction
//! encoded as a kernel variant, so the two 64x64 rules mint one node and
//! differ only in the format families they are legal for.
//!
//! Both dot lowerings coexist: `QAct::F32` (dequantize the block into
//! registers, then FMA) and `QAct::Q8Dp4a` (`Pack4xI8Clamp` the
//! activations, `Dot4I8Packed` against still-quantized weights — provably
//! not expressible as dequantize-then-dot). They do not coexist
//! *unconditionally*: the int8 packing re-encodes the activations onto a
//! coarser grid, so it is offered only where the value's
//! [`NumericContract`] licenses 8-bit operands. See [`qact_q8_dp4a`].
//!
//! `qrepack` mints the other [`QLayout`] for a weight operand in **both**
//! directions, for every format: the reference's per-device
//! `Q6K => always F32Scales` branch is deleted, so a device that never runs
//! the alignment-sensitive kernel no longer pays +0.9% bytes.
//!
//! **The geometry is a schedule domain, not a rule.** Every one of these
//! rules used to mint a domain holding exactly one point — nine hand-written
//! `(bm, bn)` tiles and one bare [`ScheduleDomain::Point`] — so a quantized
//! matmul reached extraction with no schedule decision left to make. The
//! `(bm, bn)` pairs are now generated by [`crate::domains::quantized`] from
//! lane limits, block divisibility and the exact `SgemmParams::legal`
//! footprint `verify_l1` applies; what survives here is what a *rule* is
//! actually for — which format reaches which family, and whether the shape is
//! tiled exactly or with masked edges.
//!
//! Owned by W4.

use fusor2_ir::contract_spec::partition;
use fusor2_ir::dtype::{Dtype, NumericContract, QAct, QFmt, QLayout};
use fusor2_ir::egraph::{Builder, Facts, Id, RuleTag};

use fusor2_ir::ir::level0::{EinSpec, L0, Label, LeafKind};
use fusor2_ir::ir::level1::{AccessPlan, L1, Operand, ScheduleDomain};
use fusor2_ir::ir::{Level, Node, Op, OpTag};
use fusor2_ir::rule;
use fusor2_ir::shape::{Dim, Layout};
use smallvec::SmallVec;

use crate::domains::quantized::{
    is_q5_family, q5_row_domain, qrow_domain, qtile_domain, qtile_exact_domain,
};
use crate::domains::{DomainCtx, default_planner, fold_domain};
use crate::rules::contract::{alias, contract_mnk, identity};

macro_rules! qrule {
    ($name:ident, $apply:path) => {
        rule!(
            $name,
            level = Level::L0,
            head = OpTag::Contract,
            tag = RuleTag::StrictlyLowering,
            apply = $apply,
        );
    };
}

qrule!(QMM_Q5_SMALL_SINGLE_ROW, qmm_q5_small_single_row);
qrule!(QMM_SINGLE_ROW, qmm_single_row);
qrule!(QMM_Q8_WIDE_64X128, qmm_q8_wide_64x128);
qrule!(QMM_TILE_128X128, qmm_tile_128x128);
qrule!(QMM_TILE_128X64, qmm_tile_128x64);
qrule!(QMM_TILE_64X128, qmm_tile_64x128);
qrule!(QMM_TILE_64X64_CACHED, qmm_tile_64x64_cached);
qrule!(QMM_TILE_64X32_Q4K, qmm_tile_64x32_q4k);
qrule!(QMM_TILE_64X64, qmm_tile_64x64);
qrule!(QMM_WORKGROUP, qmm_workgroup);

rule!(
    QACT_F32,
    level = Level::L1,
    head = OpTag::KQContract,
    tag = RuleTag::Additive,
    apply = qact_f32,
);

rule!(
    QACT_Q8_DP4A,
    level = Level::L1,
    head = OpTag::KQContract,
    tag = RuleTag::Additive,
    apply = qact_q8_dp4a,
);

rule!(
    QREPACK,
    level = Level::L1,
    head = OpTag::KQContract,
    tag = RuleTag::Additive,
    apply = qrepack,
);

// ---------------------------------------------------------------------------
// Format capability table
// ---------------------------------------------------------------------------

/// Whether a format's block codes can feed a `Dot4I8Packed` against
/// int8-packed activations. Must agree with W11's
/// `BlockSpec::activation`; `fusor2-tile` cannot depend on `fusor2-gguf`,
/// so the predicate is mirrored here and pinned by a test.
///
/// Q8_0 stores signed bytes outright and Q6K is the reference's proven
/// `q6k_q8_activation_dot`; the nibble formats would need an unpack before
/// the dot, which is the dequantize-then-FMA path.
pub use crate::domains::quantized::supports_q8_dp4a;

const fn is_q8_family(fmt: QFmt) -> bool {
    matches!(fmt, QFmt::Q8_0)
}

// ---------------------------------------------------------------------------
// Shared extraction of the quantized contraction's shape
// ---------------------------------------------------------------------------

struct QParts {
    fmt: QFmt,
    layout: QLayout,
    m: Dim,
    n: Dim,
    k: Dim,
    acc: Dtype,
    act: Operand,
    weight: Operand,
}

/// The `QLayout` a value carries, when it is a quantized leaf.
fn leaf_layout(b: &Builder<'_>, id: Id) -> Option<QLayout> {
    match &b.node(id).op {
        Op::L0(L0::Leaf(LeafKind::Quantized { layout, .. })) => Some(*layout),
        _ => None,
    }
}

/// The label partition [`L1::KQContract`] can address.
///
/// The node records three **extents** — [`contract_mnk`] takes the products
/// of the m, n and k labels — and its operands are plain contiguous layouts
/// ([`alias`]). Both backends read the activation at `row * k + kk` and start
/// the weight's block stream at `col * k`, so the node describes
/// `a = [m.., k..]`, `b = [n.., k..]`, `out = [m.., n..]` and nothing else:
/// once the labels are gone, a spec in any other axis order is
/// indistinguishable from the canonical one.
///
/// `mat_mul_transposed_rhs` is canonical. Its `d_lhs` is not — the adjoint
/// spec is `[m, n] x [n, k] -> [m, k]`, so the weight's contracted label is
/// its *first* axis and the block stream gets walked with `[k, rows]`
/// strides. Measured on both backends, bit-identically: for a `[3, 32]`
/// weight the gradient came back as `d_a[t] = sum_j W_flat[3 * t + j]`, the
/// weight read as `[32, 3]`.
///
/// Declining leaves the contraction to `lower_contract_generic`, whose
/// operands carry one explicit stride per label and which computes the
/// adjoint correctly. Teaching `KQContract` a transposed weight means
/// carrying the block axis on the node and honouring it in both backends'
/// block addressing; the floor already has the answer.
///
/// The quantized twin of `contract::canonical_for_mnk`, and it additionally
/// rejects a batch label: `KQContract` has no batch extent, so a batched
/// spec would drop every batch but the first.
fn canonical_for_kq(spec: &EinSpec, weight_is_rhs: bool) -> bool {
    let Ok(part) = partition(spec) else {
        return false;
    };
    if !part.batch.is_empty() || part.k.is_empty() {
        return false;
    }
    let cat = |x: &[Label], y: &[Label]| -> SmallVec<[Label; 8]> {
        x.iter().chain(y).copied().collect()
    };
    // `a` free-then-contracted, `b` free-then-contracted, and the output in
    // the order the kernel writes it: the activation's free axes index the
    // row, the weight's the column.
    if spec.a[..] != cat(&part.m, &part.k)[..] || spec.b[..] != cat(&part.n, &part.k)[..] {
        return false;
    }
    if weight_is_rhs {
        spec.out[..] == cat(&part.m, &part.n)[..]
    } else {
        spec.out[..] == cat(&part.n, &part.m)[..]
    }
}

fn qparts(b: &Builder<'_>, node: &Node, f: &Facts<'_>) -> Option<QParts> {
    let Op::L0(L0::Contract { spec, acc, a, b: rhs, .. }) = &node.op else {
        return None;
    };
    let (fa, fb) = (f.operand(0)?, f.operand(1)?);
    let mnk = contract_mnk(spec, fa, fb);

    // `a` is the activation, `b` the quantized weight — whichever slot the
    // frontend put it in. The activation is read as dense floats, so two
    // quantized operands are nobody's kernel.
    let (fmt, weight_is_rhs, weight_id, weight_facts, act_id, act_facts, m, n) =
        match (fa.dtype, fb.dtype) {
            (Dtype::Q(_), Dtype::Q(_)) => return None,
            (_, Dtype::Q(fmt)) => (fmt, true, *rhs, fb, *a, fa, mnk.m, mnk.n),
            (Dtype::Q(fmt), _) => (fmt, false, *a, fa, *rhs, fb, mnk.n, mnk.m),
            _ => return None,
        };
    if !canonical_for_kq(spec, weight_is_rhs) {
        return None;
    }
    let layout = leaf_layout(b, weight_id).unwrap_or(QLayout::Native);
    Some(QParts {
        fmt,
        layout,
        m,
        n,
        k: mnk.k,
        acc: *acc,
        act: alias(act_id, act_facts),
        weight: alias(weight_id, weight_facts),
    })
}

fn mint(b: &mut Builder<'_>, id: Id, p: QParts, sched: ScheduleDomain) -> Option<Id> {
    let op = L1::KQContract {
        fmt: p.fmt,
        layout: p.layout,
        act: QAct::F32,
        m: p.m,
        n: p.n,
        k: p.k,
        acc: p.acc,
        post: identity(p.acc),
        a: p.act,
        b: p.weight,
        sched,
    };
    let new = b.add_l1(op).ok()?;
    b.union(id, new).ok()?;
    Some(new)
}

/// The tile family's schedule domain: every `(block, cols)` this device can
/// launch on this shape, generated by [`qtile_domain`]. `None` when the
/// domain is empty, which makes the rule decline rather than mint a node
/// nothing could select.
///
/// The reference's `qmatmul_coop_tile_supported` gate — fixed subgroups plus
/// an `F32F32M8N8K8` cooperative configuration — is **deleted**, because the
/// quantized body runs no cooperative MMA: it is one accumulator per lane per
/// column and a loop over the weight's blocks. Requiring coop hardware for it
/// disqualified devices that can run it perfectly well.
fn tile_sched(p: &QParts, f: &Facts<'_>) -> Option<ScheduleDomain> {
    let cx = DomainCtx::new(f.caps(), default_planner());
    let dom = qtile_domain(p.m, p.n, p.acc, &cx);
    (!dom.params.is_empty()).then_some(ScheduleDomain::Sgemm(dom))
}

/// The same domain narrowed to the points that tile this shape exactly — no
/// masked lane, no repeated column. What the divisibility-guarded rules
/// offer, and always a subset of [`tile_sched`]'s.
fn exact_tile_sched(p: &QParts, f: &Facts<'_>) -> Option<ScheduleDomain> {
    let cx = DomainCtx::new(f.caps(), default_planner());
    let dom = qtile_exact_domain(p.m, p.n, p.acc, &cx);
    (!dom.params.is_empty()).then_some(ScheduleDomain::Sgemm(dom))
}

/// Every tile rule additionally needs more than one row: a single-row
/// contraction has no `m` fragment to load.
///
/// The `(dm, dk, dn)` divisibilities stay, and stay *rule* business: they
/// decide whether the exactly-tiled alternative exists for this shape. They
/// never decide a geometry — that is [`qtile_exact_domain`]'s job — so one
/// column short of a boundary costs the exact alternative and leaves the
/// masked one untouched, which is `qmm_tile_64x64`'s whole point.
fn tile_guard(p: &QParts, dm: u64, dk: u64, dn: u64) -> bool {
    p.m.at_least(2) && p.m.multiple_of(dm) && p.k.multiple_of(dk) && p.n.multiple_of(dn)
}

// ---------------------------------------------------------------------------
// The ten path rules
// ---------------------------------------------------------------------------

/// A single output row over a Q5-family weight, at the **narrowed** row
/// geometry its 22/24-byte blocks need.
///
/// This rule used to mint [`ScheduleDomain::Point`], and `geom_for` maps
/// `SchedPoint::Point` to `QGeom::Workgroup` — so the narrowed shape the rule
/// is named after was unreachable from the schedule it declared, and the rule
/// was a duplicate of the workgroup catch-all. [`q5_row_domain`] mints the
/// only points that reach it.
pub fn qmm_q5_small_single_row(
    b: &mut Builder<'_>,
    id: Id,
    node: &Node,
    f: &Facts<'_>,
) -> Option<Id> {
    let p = qparts(b, node, f)?;
    if !p.m.known_eq(Dim::Const(1)) || !is_q5_family(p.fmt) {
        return None;
    }
    let cx = DomainCtx::new(f.caps(), default_planner());
    let dom = q5_row_domain(p.fmt, p.n, &cx);
    if dom.params.is_empty() {
        return None;
    }
    mint(b, id, p, ScheduleDomain::Sgemv(dom))
}

/// A single output row: the quantized gemv family.
///
/// The domain is [`qrow_domain`]'s, not the dense `sgemv_domain`'s: a row
/// body gives one workgroup one output row and reaches `block * cols`
/// columns, so a point offered at a wider `n` names a launch that never
/// writes the rest. The dense domain has no such predicate because a dense
/// gemv chunks the output; this one must.
pub fn qmm_single_row(b: &mut Builder<'_>, id: Id, node: &Node, f: &Facts<'_>) -> Option<Id> {
    let p = qparts(b, node, f)?;
    if !p.m.known_eq(Dim::Const(1)) {
        return None;
    }
    let cx = DomainCtx::new(f.caps(), default_planner());
    let dom = qrow_domain(p.fmt, p.n, &cx);
    if dom.params.is_empty() {
        return None;
    }
    mint(b, id, p, ScheduleDomain::Sgemv(dom))
}

/// The wide Q8 tile. `N >= 8192` and `storage >= 32 KiB` were routing
/// thresholds in the reference; both are cost terms now.
pub fn qmm_q8_wide_64x128(b: &mut Builder<'_>, id: Id, node: &Node, f: &Facts<'_>) -> Option<Id> {
    let p = qparts(b, node, f)?;
    if !is_q8_family(p.fmt) || !tile_guard(&p, 64, 1, 128) {
        return None;
    }
    let sched = exact_tile_sched(&p, f)?;
    mint(b, id, p, sched)
}

pub fn qmm_tile_128x128(b: &mut Builder<'_>, id: Id, node: &Node, f: &Facts<'_>) -> Option<Id> {
    let p = qparts(b, node, f)?;
    if !tile_guard(&p, 128, 32, 128) {
        return None;
    }
    let sched = exact_tile_sched(&p, f)?;
    mint(b, id, p, sched)
}

pub fn qmm_tile_128x64(b: &mut Builder<'_>, id: Id, node: &Node, f: &Facts<'_>) -> Option<Id> {
    let p = qparts(b, node, f)?;
    if !tile_guard(&p, 128, 32, 64) {
        return None;
    }
    let sched = exact_tile_sched(&p, f)?;
    mint(b, id, p, sched)
}

pub fn qmm_tile_64x128(b: &mut Builder<'_>, id: Id, node: &Node, f: &Facts<'_>) -> Option<Id> {
    let p = qparts(b, node, f)?;
    if !tile_guard(&p, 64, 32, 128) {
        return None;
    }
    let sched = exact_tile_sched(&p, f)?;
    mint(b, id, p, sched)
}

/// The exactly-tiled alternative for every format the Q4K decoder does not
/// own.
pub fn qmm_tile_64x64_cached(b: &mut Builder<'_>, id: Id, node: &Node, f: &Facts<'_>) -> Option<Id> {
    let p = qparts(b, node, f)?;
    if p.fmt == QFmt::Q4K || !tile_guard(&p, 64, 32, 64) {
        return None;
    }
    let sched = exact_tile_sched(&p, f)?;
    mint(b, id, p, sched)
}

/// Q4K's narrower requirement: its 256-element super-blocks reach the exact
/// alternative at a looser column divisibility than the other formats.
pub fn qmm_tile_64x32_q4k(b: &mut Builder<'_>, id: Id, node: &Node, f: &Facts<'_>) -> Option<Id> {
    let p = qparts(b, node, f)?;
    if p.fmt != QFmt::Q4K || !tile_guard(&p, 64, 32, 32) {
        return None;
    }
    let sched = exact_tile_sched(&p, f)?;
    mint(b, id, p, sched)
}

/// The tiled alternative with no divisibility requirement — edge lanes mask.
/// This is what makes N = 8191 land next to N = 8192 instead of several arms
/// down a first-match list: its domain is a pure function of the device and
/// the output extent, so a prime `n` loses the *exact* alternative and not a
/// single geometry.
pub fn qmm_tile_64x64(b: &mut Builder<'_>, id: Id, node: &Node, f: &Facts<'_>) -> Option<Id> {
    let p = qparts(b, node, f)?;
    if !p.m.at_least(2) {
        return None;
    }
    let sched = tile_sched(&p, f)?;
    mint(b, id, p, sched)
}

/// The catch-all: a workgroup-wide fold over K, legal everywhere.
pub fn qmm_workgroup(b: &mut Builder<'_>, id: Id, node: &Node, f: &Facts<'_>) -> Option<Id> {
    let p = qparts(b, node, f)?;
    let cx = DomainCtx::new(f.caps(), default_planner());
    let sched = ScheduleDomain::Fold(fold_domain(p.k, &cx));
    mint(b, id, p, sched)
}

// ---------------------------------------------------------------------------
// Activation packing and repacking
// ---------------------------------------------------------------------------

fn with_act(b: &mut Builder<'_>, id: Id, node: &Node, want: QAct) -> Option<Id> {
    let Op::L1(l1) = &node.op else { return None };
    let L1::KQContract { act, .. } = l1 else {
        return None;
    };
    if *act == want {
        return None;
    }
    let mut rebuilt = l1.clone();
    if let L1::KQContract { act, .. } = &mut rebuilt {
        *act = want;
    }
    let new = b.add_l1(rebuilt).ok()?;
    b.union(id, new).ok()?;
    Some(new)
}

/// Dequantize the block into registers, then FMA.
pub fn qact_f32(b: &mut Builder<'_>, id: Id, node: &Node, f: &Facts<'_>) -> Option<Id> {
    let _ = f;
    with_act(b, id, node, QAct::F32)
}

/// Pack activations to int8 and dot against still-quantized weights. The
/// reference's hardcoded comment about compounding error becomes a
/// [`NumericContract`] guard: only a value that licenses 8-bit **operands**
/// reaches the int path.
///
/// The guard used to be `RELAXED.allows(..)`, which asks whether the value
/// permits reassociation and FMA contraction. It does not follow. Both of
/// those are exact to rounding; re-encoding the activations onto an int8 grid
/// is not, and the error does not shrink with a wider accumulator. Measured
/// on the `matmul::q_mat_mul_rank1` shape (Q8_0, k = 32): the exact f32 dot
/// is 0.48197886 and the CPU device value under this packing is 0.47361845,
/// bit-identical to the ideal int8-activation dot computed host-side
/// (`scale = max|a| / 127`, round-half-away, clamp, rescale) — 1.7% relative
/// against a case bar of 1e-3. The kernel is right; what was wrong was the
/// permission it was minted under.
///
/// So the guard now names the axis it means. See
/// [`NumericContract::RELAXED_OPERANDS`]: nothing mints that contract yet, so
/// this rule is offered nowhere until a frontend opts a value into it.
pub fn qact_q8_dp4a(b: &mut Builder<'_>, id: Id, node: &Node, f: &Facts<'_>) -> Option<Id> {
    let Op::L1(L1::KQContract { fmt, .. }) = &node.op else {
        return None;
    };
    if !supports_q8_dp4a(*fmt) {
        return None;
    }
    if !NumericContract::RELAXED_OPERANDS.allows(f.own().numeric) {
        return None;
    }
    with_act(b, id, node, QAct::Q8Dp4a)
}

/// Whether a `Pack` operand access is realized by a launch anywhere in the
/// pipeline. It is not, which is why [`qrepack`] declines. See the comment
/// inside it.
const REPACK_HAS_A_LAUNCH: bool = false;

/// Mint the other [`QLayout`] for the weight operand, wrapping the source
/// in a repacking access. Legal for every format in both directions; the
/// cost is the repack bytes — derivable from `fmt` and the two
/// `QFmt::block_bytes` — amortized over `Persistence::Persistent`.
pub fn qrepack(b: &mut Builder<'_>, id: Id, node: &Node, f: &Facts<'_>) -> Option<Id> {
    let _ = f;
    // **Nothing executes the repack yet.** `AccessPlan::Pack { into }` appears
    // in `plan.rs` only in the plan hash and the symbol walk — no launch is
    // derived for it and neither emitter honours it — so the node this rule
    // mints tells the kernel the weight is in `want` while the buffer still
    // holds the original bytes. Selecting it decoded Q4_0/Q5_0 native blocks as
    // if their scales were f32: NaN on the CPU, ~1e-8 on the GPU.
    //
    // The rewrite itself is right; what is missing is a materialization step,
    // because the repacked image is a *new buffer* produced by its own launch —
    // `realize`/`plan` work, not a rewrite.
    // `qrepack_needs_a_repack_launch_that_does_not_exist` pins this boundary
    // and fails the moment one appears.
    if !REPACK_HAS_A_LAUNCH {
        return None;
    }
    let Op::L1(l1) = &node.op else { return None };
    let L1::KQContract { layout, b: weight, .. } = l1 else {
        return None;
    };
    // A repack of a repack is not a second alternative: the edge already
    // carries one packing step and cannot carry two.
    if !matches!(weight.access, AccessPlan::Alias) {
        return None;
    }
    let want = match layout {
        QLayout::Native => QLayout::F32Scales,
        QLayout::F32Scales => QLayout::Native,
    };
    // The repacked buffer is a fresh contiguous byte image of the weight;
    // the `Pack` access is where the repack happens.
    let into = Layout::contiguous(weight.layout.shape());
    let mut rebuilt = l1.clone();
    if let L1::KQContract { layout, b: weight, .. } = &mut rebuilt {
        *layout = want;
        weight.access = AccessPlan::Pack { into };
    }
    let new = b.add_l1(rebuilt).ok()?;
    b.union(id, new).ok()?;
    Some(new)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domains::quantized::{QLanes, tile_lanes};
    use crate::domains::testing::apple_caps;
    use crate::rules::TILE_RULES;
    use crate::rules::testing::{Fixture, l1_of};
    use fusor2_ir::ir::level0::{EinSpec, Label};
    use smallvec::smallvec;
    use std::collections::BTreeSet;

    fn qspec() -> EinSpec {
        EinSpec {
            a: smallvec![Label(b'm'), Label(b'k')],
            b: smallvec![Label(b'n'), Label(b'k')],
            out: smallvec![Label(b'm'), Label(b'n')],
        }
    }

    fn build(m: u64, k: u64, n: u64, fmt: QFmt) -> (Fixture, Id) {
        let mut fx = Fixture::new(apple_caps());
        let act = fx.buffer(Dtype::F32, &[m, k]);
        let w = fx.quantized(fmt, QLayout::Native, &[n, k]);
        let c = fx.contract(qspec(), Dtype::F32, act, w);
        fx.apply_all(TILE_RULES, c);
        (fx, c)
    }

    fn qnodes(fx: &Fixture, id: Id) -> Vec<L1> {
        fx.chain(id)
            .into_iter()
            .filter_map(|m| l1_of(fx, m))
            .filter(|m| matches!(m, L1::KQContract { .. }))
            .collect()
    }

    fn has_workgroup(nodes: &[L1]) -> bool {
        nodes.iter().any(|n| {
            matches!(
                n,
                L1::KQContract {
                    sched: ScheduleDomain::Fold(_),
                    ..
                }
            )
        })
    }

    /// The distinct `(block, cols)` a chain's tiled alternatives offer,
    /// ignoring the activation-packing and layout variants stacked on each.
    /// `(block, cols)` — not `(bm, bn)` — because it is what the emitter
    /// reads; see `domains::quantized`.
    fn tile_geoms(nodes: &[L1]) -> BTreeSet<QLanes> {
        let mut out = BTreeSet::new();
        for n in nodes {
            if let L1::KQContract {
                sched: ScheduleDomain::Sgemm(d),
                ..
            } = n
            {
                out.extend(d.params.iter().map(tile_lanes));
            }
        }
        out
    }

    /// Whether a rule body fires on this node, asked of the rule directly.
    fn fires(
        fx: &mut Fixture,
        id: Id,
        rule: fn(&mut Builder<'_>, Id, &Node, &Facts<'_>) -> Option<Id>,
    ) -> bool {
        let node = fx.graph.node(id).clone();
        let facts = fx.graph.facts_view(id, &fx.caps);
        let mut b = fx.graph.builder(&fx.caps);
        rule(&mut b, id, &node, &facts).is_some()
    }

    #[test]
    fn n_8191_and_8192_have_the_same_candidate_set() {
        let (fx_a, a) = build(128, 1024, 8191, QFmt::Q8_0);
        let (fx_b, b) = build(128, 1024, 8192, QFmt::Q8_0);
        let na = qnodes(&fx_a, a);
        let nb = qnodes(&fx_b, b);

        assert!(has_workgroup(&na), "8191 lost the workgroup catch-all");
        assert!(has_workgroup(&nb), "8192 lost the workgroup catch-all");
        let (ga, gb) = (tile_geoms(&na), tile_geoms(&nb));
        assert!(!ga.is_empty(), "8191 lost every tile rule");
        assert!(!gb.is_empty(), "8192 lost every tile rule");
        // Continuity, now structural rather than counted: the masked domain
        // is a function of the device and the output extent, so one column
        // short of a divisibility boundary loses the *exactly tiled*
        // alternative and not one geometry.
        assert_eq!(ga, gb, "8191 {ga:?} vs 8192 {gb:?}: the cliff is back");
        assert!(
            ga.iter().any(|l| l.block == 1024),
            "the widest launchable block must survive at N = 8191: {ga:?}"
        );
    }

    /// At a round shape every divisibility-guarded rule fires, and the
    /// alternative it mints tiles the shape exactly — no masked lane, no
    /// column computed twice.
    #[test]
    fn every_divisible_tile_rule_fires_at_a_round_shape() {
        let (mut fx, c) = build(256, 1024, 256, QFmt::Q8_0);
        for rule in [
            qmm_q8_wide_64x128 as fn(&mut Builder<'_>, Id, &Node, &Facts<'_>) -> Option<Id>,
            qmm_tile_128x128,
            qmm_tile_128x64,
            qmm_tile_64x128,
            qmm_tile_64x64_cached,
            qmm_tile_64x64,
        ] {
            assert!(fires(&mut fx, c, rule), "a guarded tile rule declined");
        }
        let nodes = qnodes(&fx, c);
        let exact: Vec<&L1> = nodes
            .iter()
            .filter(|n| {
                matches!(n, L1::KQContract { sched: ScheduleDomain::Sgemm(d), .. }
                    if d.params.iter().all(|p| {
                        let l = tile_lanes(p);
                        (256u64 * 256).is_multiple_of(u64::from(l.block))
                            && 256u64.is_multiple_of(u64::from(l.cols))
                    }))
            })
            .collect();
        assert!(!exact.is_empty(), "no exactly-tiled alternative");
        assert!(!tile_geoms(&nodes).is_empty());
        assert!(has_workgroup(&nodes));
    }

    /// The `cached` distinction was a pipeline-cache slot encoded as a kernel
    /// variant; what survives is a format reach. Q4K reaches the exactly
    /// tiled alternative at its own column divisibility, and the rule that
    /// excludes it declines.
    #[test]
    fn q4k_takes_the_narrow_tile_and_not_the_cached_one() {
        let (mut fx, c) = build(256, 1024, 256, QFmt::Q4K);
        assert!(
            fires(&mut fx, c, qmm_tile_64x32_q4k),
            "Q4K must reach its own tile rule"
        );
        assert!(
            !fires(&mut fx, c, qmm_tile_64x64_cached),
            "the cached rule must still decline for Q4K"
        );
        // The geometry is not lost with it: the masked alternative offers the
        // same points to every format.
        let (fx_q8, c8) = build(256, 1024, 256, QFmt::Q8_0);
        assert_eq!(
            tile_geoms(&qnodes(&fx, c)),
            tile_geoms(&qnodes(&fx_q8, c8)),
            "the tile geometry must not depend on the format"
        );
    }

    /// A tiled quantized alternative declares the workgroup it launches. The
    /// shipped table declared 4,096- and 16,384-lane workgroups on a
    /// 1,024-lane device and let the emitter clamp them; nothing may do that
    /// again.
    #[test]
    fn no_alternative_declares_a_workgroup_the_device_cannot_launch() {
        let caps = apple_caps();
        let cap = caps.limits.max_compute_invocations_per_workgroup;
        for (m, k, n, fmt) in [
            (256u64, 1024u64, 256u64, QFmt::Q8_0),
            (128, 1024, 8191, QFmt::Q4K),
            (2, 32, 3, QFmt::Q4_0),
        ] {
            let (fx, c) = build(m, k, n, fmt);
            for l in tile_geoms(&qnodes(&fx, c)) {
                assert!(l.block <= cap, "{m}x{k}x{n} {fmt:?} declares {l:?}");
                assert_eq!(l.block % caps.subgroup_width(), 0, "{l:?}");
            }
        }
    }

    /// The tiny conformance shape: a 6-element output must not be handed a
    /// 1,024-lane workgroup, and a 3-column output must not be handed a
    /// 4-column lane.
    #[test]
    fn a_tiny_shape_gets_a_tiny_domain() {
        let (fx, c) = build(2, 32, 3, QFmt::Q8_0);
        let geoms = tile_geoms(&qnodes(&fx, c));
        assert!(!geoms.is_empty(), "the narrowest block must survive");
        for l in &geoms {
            assert_eq!(l.block, 32, "{l:?} is wider than the whole output");
            assert!(l.cols <= 3, "{l:?} owns more columns than the matrix has");
        }
        let (fx_big, c_big) = build(128, 1024, 8192, QFmt::Q8_0);
        assert_ne!(
            geoms,
            tile_geoms(&qnodes(&fx_big, c_big)),
            "two shapes three orders of magnitude apart got the same domain"
        );
    }

    #[test]
    fn single_row_shapes_have_no_tiles() {
        let (fx, c) = build(1, 1024, 4096, QFmt::Q8_0);
        assert!(tile_geoms(&qnodes(&fx, c)).is_empty());
    }

    /// The row family reaches `block * cols` output columns and no more —
    /// one workgroup per output row, one subgroup of lanes. Both row rules
    /// fire where that covers the output.
    #[test]
    fn single_row_shapes_take_the_gemv_family() {
        // Half a subgroup is what the Q5 narrowed shape covers.
        let (mut fx, c) = build(1, 1024, 16, QFmt::Q5_0);
        assert!(
            fires(&mut fx, c, qmm_single_row),
            "qmm_single_row must fire at m = 1"
        );
        assert!(
            fires(&mut fx, c, qmm_q5_small_single_row),
            "qmm_q5_small_single_row must fire for a Q5 weight at m = 1"
        );
        let nodes = qnodes(&fx, c);
        assert!(
            nodes
                .iter()
                .any(|n| matches!(n, L1::KQContract { sched: ScheduleDomain::Sgemv(_), .. })),
            "the row family must reach the chain"
        );
        // Q8_0 reaches `Q8Wide` — two subgroups, four columns per lane — so
        // it covers eight times as many columns as the plain single row.
        let (mut fx, c) = build(1, 1024, 256, QFmt::Q8_0);
        assert!(fires(&mut fx, c, qmm_single_row));
    }

    /// The row shapes give one workgroup one output row, so a wide `n` is
    /// not something they can compute at all — the rule declines instead of
    /// minting an alternative that would leave columns unwritten. The
    /// workgroup catch-all, which walks the flattened output, still fires.
    #[test]
    fn the_row_family_declines_a_width_it_cannot_cover() {
        let (mut fx, c) = build(1, 1024, 4096, QFmt::Q5_0);
        assert!(!fires(&mut fx, c, qmm_single_row));
        assert!(!fires(&mut fx, c, qmm_q5_small_single_row));
        let nodes = qnodes(&fx, c);
        assert!(
            !nodes
                .iter()
                .any(|n| matches!(n, L1::KQContract { sched: ScheduleDomain::Sgemv(_), .. })),
            "a row alternative at n = 4096 would never write 4064 of its columns"
        );
        assert!(has_workgroup(&nodes), "the catch-all must still cover it");
    }

    /// A `Semantics` that stamps [`NumericContract::RELAXED_OPERANDS`] on
    /// every value — the licence a caller opts into to allow the activations
    /// onto an 8-bit grid. Everything else is [`TestSemantics`].
    struct LicensesInt8Operands;

    impl fusor2_ir::ir::Semantics for LicensesInt8Operands {
        fn children(&self, op: &Op) -> fusor2_ir::ir::Children {
            crate::rules::testing::TestSemantics.children(op)
        }
        fn infer(
            &self,
            op: &Op,
            ins: &[fusor2_ir::facts::ValueFacts],
        ) -> fusor2_ir::Result<fusor2_ir::facts::ValueFacts> {
            Ok(crate::rules::testing::TestSemantics
                .infer(op, ins)?
                .with_numeric(NumericContract::RELAXED_OPERANDS))
        }
        fn work(
            &self,
            op: &Op,
            ins: &[fusor2_ir::facts::ValueFacts],
            out: &fusor2_ir::facts::ValueFacts,
        ) -> fusor2_ir::facts::Work {
            crate::rules::testing::TestSemantics.work(op, ins, out)
        }
        fn verify(&self, cx: &fusor2_ir::ir::VerifyCtx<'_>) -> fusor2_ir::Result<()> {
            crate::rules::testing::TestSemantics.verify(cx)
        }
        fn effect(&self, op: &Op) -> fusor2_ir::ir::level1::Effect {
            crate::rules::testing::TestSemantics.effect(op)
        }
    }

    /// The int8 activation dot is licensed by an **operand-precision** term,
    /// not by permission to reassociate.
    ///
    /// Both directions, because only one of them is a law about a rule and the
    /// other is a law about the whole default pipeline: under the contract
    /// every value carries today the packing is not offered at all, and it
    /// appears the moment — and only the moment — a value licenses 8-bit
    /// operands. `QAct::F32` is unconditional either way.
    ///
    /// The measured content of the guard: at Q8_0 the packing costs 1.7%
    /// relative on `matmul::q_mat_mul_rank1`, which is not a rounding effect
    /// and does not shrink with a wider accumulator.
    #[test]
    fn q8_dp4a_needs_an_operand_precision_licence() {
        let (fx, c) = build(128, 1024, 8192, QFmt::Q8_0);
        let nodes = qnodes(&fx, c);
        let has = |nodes: &[L1], want: QAct| {
            nodes
                .iter()
                .any(|n| matches!(n, L1::KQContract { act, .. } if *act == want))
        };
        assert!(has(&nodes, QAct::F32), "the f32 path is unconditional");
        assert!(
            !has(&nodes, QAct::Q8Dp4a),
            "RELAXED permits reassociation and FMA contraction, neither of which \
             licenses re-encoding the activations onto an int8 grid"
        );

        let mut fx = Fixture::new(apple_caps());
        fx.graph = fusor2_ir::egraph::EGraph::new(std::sync::Arc::new(LicensesInt8Operands));
        let act = fx.buffer(Dtype::F32, &[128, 1024]);
        let w = fx.quantized(QFmt::Q8_0, QLayout::Native, &[8192, 1024]);
        let c = fx.contract(qspec(), Dtype::F32, act, w);
        assert_eq!(
            fx.graph.facts(c).numeric,
            NumericContract::RELAXED_OPERANDS,
            "the licensing fixture must actually license"
        );
        fx.apply_all(TILE_RULES, c);
        let nodes = qnodes(&fx, c);
        assert!(has(&nodes, QAct::F32));
        assert!(
            has(&nodes, QAct::Q8Dp4a),
            "a licensed value must still reach the int8 dot"
        );
    }

    #[test]
    fn no_dp4a_for_a_nibble_format() {
        let (fx, c) = build(128, 1024, 8192, QFmt::Q4_0);
        let nodes = qnodes(&fx, c);
        assert!(!nodes.iter().any(|n| matches!(
            n,
            L1::KQContract {
                act: QAct::Q8Dp4a,
                ..
            }
        )));
    }

    /// The boundary [`qrepack`] is disabled at, asserted rather than asserted
    /// away.
    ///
    /// The rule is bidirectional and correct as a *rewrite*; what is missing is
    /// the launch that produces the repacked byte image, so the operand it
    /// mints names a packing the buffer does not have. Every weight therefore
    /// keeps exactly the layout its leaf carries. When a repack launch lands,
    /// this test fails and `qrepack`'s early return comes out with it.
    #[test]
    fn qrepack_needs_a_repack_launch_that_does_not_exist() {
        let (fx, c) = build(128, 1024, 4096, QFmt::Q6K);
        let nodes = qnodes(&fx, c);
        assert!(
            nodes
                .iter()
                .any(|n| matches!(n, L1::KQContract { layout: QLayout::Native, .. })),
            "the native operand must survive"
        );
        assert!(
            !nodes
                .iter()
                .any(|n| matches!(n, L1::KQContract { layout: QLayout::F32Scales, .. })),
            "no alternative may claim a packing the buffer does not hold"
        );
        assert!(
            !nodes
                .iter()
                .any(|n| matches!(n, L1::KQContract { b, .. } if !matches!(b.access, AccessPlan::Alias))),
            "a quantized weight operand may only alias while nothing repacks it"
        );

        // And the reverse direction is equally absent: an F32Scales weight
        // keeps F32Scales.
        let mut fx = Fixture::new(apple_caps());
        let act = fx.buffer(Dtype::F32, &[128, 1024]);
        let w = fx.quantized(QFmt::Q6K, QLayout::F32Scales, &[4096, 1024]);
        let c = fx.contract(qspec(), Dtype::F32, act, w);
        fx.apply_all(TILE_RULES, c);
        let nodes = qnodes(&fx, c);
        assert!(
            !nodes
                .iter()
                .any(|n| matches!(n, L1::KQContract { layout: QLayout::Native, .. })),
            "an F32Scales Q6K operand must not mint a Native alternative yet"
        );
    }

    #[test]
    fn repack_bytes_are_derivable_from_the_node() {
        // W6 divides these by the weight's expected reuse; W4 only has to
        // leave them recoverable.
        for fmt in QFmt::ALL {
            let native = fmt.block_bytes(QLayout::Native);
            let widened = fmt.block_bytes(QLayout::F32Scales);
            assert!(widened > native, "{fmt:?}");
        }
    }

    #[test]
    fn dense_contractions_mint_no_quantized_node() {
        let mut fx = Fixture::new(apple_caps());
        let a = fx.buffer(Dtype::F32, &[128, 1024]);
        let b = fx.buffer(Dtype::F32, &[4096, 1024]);
        let c = fx.contract(qspec(), Dtype::F32, a, b);
        fx.apply_all(TILE_RULES, c);
        assert!(qnodes(&fx, c).is_empty());
    }
}
